apiVersion: v1
kind: Service
metadata:
  name: people-api
  labels:
    app: people-api
spec:
  ports:
    - port: 8080
      name: api
  selector:
    app: people-api
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: people-api
  labels:
    app: people-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: people-api
  template:
    metadata:
      labels:
        app: people-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: people-api
      nodeSelector:
        "cloud.google.com/gke-preemptible": "true"
      containers:
        - name: people-api
          args: [
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
	        ]
          image: ngbook/people-api:k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: api-port
