// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ngbook/fruit/proto/fruit.api.proto

/*
Package fruit_api is a generated protocol buffer package.

It is generated from these files:
	ngbook/fruit/proto/fruit.api.proto

It has these top-level messages:
	Fruit
	GetListReq
	GetListRsp
	CommonRsp
*/
package fruit_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Fruit struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Pic  string `protobuf:"bytes,4,opt,name=pic" json:"pic,omitempty"`
}

func (m *Fruit) Reset()                    { *m = Fruit{} }
func (m *Fruit) String() string            { return proto.CompactTextString(m) }
func (*Fruit) ProtoMessage()               {}
func (*Fruit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Fruit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Fruit) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Fruit) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

type GetListReq struct {
}

func (m *GetListReq) Reset()                    { *m = GetListReq{} }
func (m *GetListReq) String() string            { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()               {}
func (*GetListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetListRsp struct {
	Fruits []*Fruit `protobuf:"bytes,1,rep,name=fruits" json:"fruits,omitempty"`
}

func (m *GetListRsp) Reset()                    { *m = GetListRsp{} }
func (m *GetListRsp) String() string            { return proto.CompactTextString(m) }
func (*GetListRsp) ProtoMessage()               {}
func (*GetListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetListRsp) GetFruits() []*Fruit {
	if m != nil {
		return m.Fruits
	}
	return nil
}

type CommonRsp struct {
}

func (m *CommonRsp) Reset()                    { *m = CommonRsp{} }
func (m *CommonRsp) String() string            { return proto.CompactTextString(m) }
func (*CommonRsp) ProtoMessage()               {}
func (*CommonRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Fruit)(nil), "Fruit")
	proto.RegisterType((*GetListReq)(nil), "GetListReq")
	proto.RegisterType((*GetListRsp)(nil), "GetListRsp")
	proto.RegisterType((*CommonRsp)(nil), "CommonRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FruitService service

type FruitServiceClient interface {
	GetList(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*GetListRsp, error)
	RspError(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*CommonRsp, error)
	RspErrorCode(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*CommonRsp, error)
}

type fruitServiceClient struct {
	c           client.Client
	serviceName string
}

func NewFruitServiceClient(serviceName string, c client.Client) FruitServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "fruitservice"
	}
	return &fruitServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *fruitServiceClient) GetList(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*GetListRsp, error) {
	req := c.c.NewRequest(c.serviceName, "FruitService.GetList", in)
	out := new(GetListRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fruitServiceClient) RspError(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.serviceName, "FruitService.RspError", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fruitServiceClient) RspErrorCode(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.serviceName, "FruitService.RspErrorCode", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FruitService service

type FruitServiceHandler interface {
	GetList(context.Context, *GetListReq, *GetListRsp) error
	RspError(context.Context, *GetListReq, *CommonRsp) error
	RspErrorCode(context.Context, *GetListReq, *CommonRsp) error
}

func RegisterFruitServiceHandler(s server.Server, hdlr FruitServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FruitService{hdlr}, opts...))
}

type FruitService struct {
	FruitServiceHandler
}

func (h *FruitService) GetList(ctx context.Context, in *GetListReq, out *GetListRsp) error {
	return h.FruitServiceHandler.GetList(ctx, in, out)
}

func (h *FruitService) RspError(ctx context.Context, in *GetListReq, out *CommonRsp) error {
	return h.FruitServiceHandler.RspError(ctx, in, out)
}

func (h *FruitService) RspErrorCode(ctx context.Context, in *GetListReq, out *CommonRsp) error {
	return h.FruitServiceHandler.RspErrorCode(ctx, in, out)
}

func init() { proto.RegisterFile("ngbook/fruit/proto/fruit.api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x27, 0x74, 0xac, 0xce, 0x6d, 0x17, 0x72, 0x57, 0xc1, 0x85, 0x0c, 0x81, 0x81, 0x11,
	0x24, 0x85, 0xfa, 0x04, 0x52, 0xd4, 0x8d, 0xab, 0xf8, 0x04, 0xfd, 0x89, 0x12, 0xa4, 0xbd, 0x31,
	0x89, 0xbe, 0x82, 0xaf, 0x2d, 0x49, 0xab, 0xc5, 0xcd, 0xec, 0xbe, 0xf3, 0xe5, 0x70, 0x0f, 0x04,
	0xc4, 0xf4, 0xd6, 0x11, 0xbd, 0x57, 0xaf, 0xee, 0xd3, 0x84, 0xca, 0x3a, 0x0a, 0x34, 0xb3, 0x6c,
	0xad, 0x91, 0x29, 0x8b, 0x7b, 0x38, 0x7b, 0x8c, 0x0a, 0x11, 0xb6, 0x53, 0x3b, 0x6a, 0xce, 0xf6,
	0xec, 0xb8, 0x53, 0x89, 0xa3, 0x1b, 0xb4, 0xef, 0x79, 0x36, 0xbb, 0xc8, 0x78, 0x09, 0x99, 0x35,
	0x3d, 0xdf, 0x26, 0x15, 0x51, 0x94, 0x00, 0x4f, 0x3a, 0x3c, 0x1b, 0x1f, 0x94, 0xfe, 0x10, 0xb7,
	0x6b, 0xf2, 0x16, 0xaf, 0x21, 0x4f, 0x8b, 0x9e, 0xb3, 0x7d, 0x76, 0x2c, 0xea, 0x5c, 0xa6, 0x35,
	0xb5, 0x58, 0x51, 0xc0, 0xae, 0xa1, 0x71, 0xa4, 0x49, 0x79, 0x5b, 0x7f, 0x33, 0x28, 0xd3, 0xf3,
	0x8b, 0x76, 0x5f, 0xa6, 0xd7, 0x78, 0x80, 0xf3, 0xe5, 0x16, 0x16, 0x72, 0xdd, 0xb8, 0x5a, 0x83,
	0xb7, 0x62, 0x83, 0x07, 0xb8, 0x50, 0xde, 0x3e, 0x38, 0x47, 0xee, 0x7f, 0x0f, 0xe4, 0xdf, 0x71,
	0xb1, 0xc1, 0x1b, 0x28, 0x7f, 0x6b, 0x0d, 0x0d, 0xfa, 0x44, 0xb5, 0xcb, 0xd3, 0xe7, 0xdc, 0xfd,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x12, 0xb4, 0x7f, 0x42, 0x01, 0x00, 0x00,
}
