// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ngbook/proto/fruit/fruit.srv.proto

/*
Package fruit_srv is a generated protocol buffer package.

It is generated from these files:
	ngbook/proto/fruit/fruit.srv.proto

It has these top-level messages:
	Fruit
	GetListReq
	GetListRsp
*/
package fruit_srv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Fruit struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Pic  string `protobuf:"bytes,4,opt,name=pic" json:"pic,omitempty"`
}

func (m *Fruit) Reset()                    { *m = Fruit{} }
func (m *Fruit) String() string            { return proto.CompactTextString(m) }
func (*Fruit) ProtoMessage()               {}
func (*Fruit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Fruit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Fruit) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Fruit) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

type GetListReq struct {
}

func (m *GetListReq) Reset()                    { *m = GetListReq{} }
func (m *GetListReq) String() string            { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()               {}
func (*GetListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetListRsp struct {
	Fruits []*Fruit `protobuf:"bytes,1,rep,name=fruits" json:"fruits,omitempty"`
}

func (m *GetListRsp) Reset()                    { *m = GetListRsp{} }
func (m *GetListRsp) String() string            { return proto.CompactTextString(m) }
func (*GetListRsp) ProtoMessage()               {}
func (*GetListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetListRsp) GetFruits() []*Fruit {
	if m != nil {
		return m.Fruits
	}
	return nil
}

func init() {
	proto.RegisterType((*Fruit)(nil), "Fruit")
	proto.RegisterType((*GetListReq)(nil), "GetListReq")
	proto.RegisterType((*GetListRsp)(nil), "GetListRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FruitService service

type FruitServiceClient interface {
	GetList(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*GetListRsp, error)
}

type fruitServiceClient struct {
	c           client.Client
	serviceName string
}

func NewFruitServiceClient(serviceName string, c client.Client) FruitServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "fruitservice"
	}
	return &fruitServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *fruitServiceClient) GetList(ctx context.Context, in *GetListReq, opts ...client.CallOption) (*GetListRsp, error) {
	req := c.c.NewRequest(c.serviceName, "FruitService.GetList", in)
	out := new(GetListRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FruitService service

type FruitServiceHandler interface {
	GetList(context.Context, *GetListReq, *GetListRsp) error
}

func RegisterFruitServiceHandler(s server.Server, hdlr FruitServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FruitService{hdlr}, opts...))
}

type FruitService struct {
	FruitServiceHandler
}

func (h *FruitService) GetList(ctx context.Context, in *GetListReq, out *GetListRsp) error {
	return h.FruitServiceHandler.GetList(ctx, in, out)
}

func init() { proto.RegisterFile("ngbook/proto/fruit/fruit.srv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xca, 0x4b, 0x4f, 0xca,
	0xcf, 0xcf, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2b, 0x2a, 0xcd, 0x2c, 0x81, 0x90,
	0x7a, 0xc5, 0x45, 0x65, 0x7a, 0x60, 0x51, 0x25, 0x47, 0x2e, 0x56, 0x37, 0x90, 0x90, 0x90, 0x10,
	0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x0d, 0x12,
	0x4b, 0x49, 0x2d, 0x4e, 0x96, 0x60, 0x86, 0x88, 0x81, 0xd8, 0x42, 0x02, 0x5c, 0xcc, 0x05, 0x99,
	0xc9, 0x12, 0x2c, 0x60, 0x21, 0x10, 0x53, 0x89, 0x87, 0x8b, 0xcb, 0x3d, 0xb5, 0xc4, 0x27, 0xb3,
	0xb8, 0x24, 0x28, 0xb5, 0x50, 0x49, 0x07, 0xc1, 0x2b, 0x2e, 0x10, 0x92, 0xe3, 0x62, 0x03, 0xdb,
	0x58, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa6, 0x07, 0xb6, 0x2d, 0x08, 0x2a, 0x6a,
	0x64, 0xca, 0xc5, 0x03, 0x16, 0x08, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x52, 0xe5, 0x62,
	0x87, 0xea, 0x16, 0xe2, 0xd6, 0x43, 0x98, 0x2a, 0x85, 0xe0, 0x14, 0x17, 0x28, 0x31, 0x24, 0xb1,
	0x81, 0x1d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xb8, 0x07, 0x6a, 0xe2, 0x00, 0x00,
	0x00,
}
