apiVersion: v1
kind: Service
metadata:
  name: fruit-api
  labels:
    app: fruit-api
spec:
  ports:
    - port: 8080
      name: api
  selector:
    app: fruit-api
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fruit-api
  labels:
    app: fruit-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fruit-api
  template:
    metadata:
      labels:
        app: fruit-api
    spec:
      nodeSelector:
        "cloud.google.com/gke-preemptible": "true"
      containers:
        - name: fruit-api
          args: [
            # "/fruit",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
	        ]
          image: ngbook/fruit-api:k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: api-port
