apiVersion: v1
kind: Service
metadata:
  name: fruit-api
  labels:
    app: fruit-api
spec:
  ports:
    - port: 8080
      name: api
  selector:
    app: fruit-api
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fruit-api
  labels:
    app: fruit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit-api
  template:
    metadata:
      labels:
        app: fruit-api
    spec:
      nodeSelector:
        "cloud.google.com/gke-preemptible": "true"
      containers:
        - name: fruit-api
          args: [
            "/fruit",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
	        ]
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: api-port
        - name: health
          command: [
		        "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=fruit-api",
            "--server_address=0.0.0.0:8080"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
